An aliased Commit to save time

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,13 @@
 #!bin/bash
+
+if [[ -z "$PYFILE"]]; then
+	echo "Error: Environment variable not set"
+	exit 1
+fi
+
+if [[! -f "$PYFILE"]]; then
+	echo "Error: File assosciated with $PYFILE does not exist"
+	exit 1
+fi
+
 python $PYFILE
